kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: react-starter-vite
  name: react-starter-vite
  labels:
    app: react-starter-vite

spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-starter-vite
  template:
    metadata:
      labels:
        app: react-starter-vite
    spec:
      containers:
        - name: react-starter-vite
          image: {{.Values.image}}
          ports:
            - name: web
              containerPort: 8080
