apiVersion: v1
kind: Service
metadata:
  name: react-starter-vite
  namespace: react-starter-vite

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: react-starter-vite
