server:
  persistentVolume:
    enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: false
alertmanager:
  enabled: false
kube-state-metrics:
  enabled: false
forceNamespace: prometheus
