hostNetwork: true
ports:
  web:
    port: 80
  websecure:
    port: 443
  metrics:
    port: 9101

securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
service:
  type: ClusterIP
