apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingresswhoami

spec:
  entryPoints:
    - web

  routes:
    - match: PathPrefix(`/whoami`)
      kind: Rule
      services:
        - name: whoami
          port: 80
