env:
  email: "1995navinkumar@gmail.com"
  password: "${postgresAdminPassword}"
service:
  type: NodePort
  nodePort: 32000
persistentVolume:
  enabled: false
ingress:
  enabled: false
  hosts:
    - host: gently-concise-dogfish.ngrok-free.app
      paths:
        - path: /pgadmin
          pathType: Prefix
VolumePermissions:
  enabled: true
