auth:
  enablePostgresUser: true
  postgresPassword: "${postgresAdminPassword}"
  username: "${postgresUser}"
  password: "${postgresPassword}"
primary:
  persistence:
    size: 3Gi
    storageClass: local-storage-class
volumePermissions:
  enabled: true
