apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          args: ["--dbpath", "/data/db"]
          env:
          # Todo - replace with secrets
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume

  volumeClaimTemplates:
    - metadata:
        name: mongo-volume
      spec:
        storageClassName: "db-storage"
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 3Gi
