apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test
  annotations:
    nginx.org/rewrites: "serviceName=nginx-service rewrite=/"
spec:
  ingressClassName: nginx
  rules:
    - host: gently-concise-dogfish.ngrok-free.app
      http:
        paths:
          - path: /test/
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 8082
          - path: /prometheus/
            pathType: Prefix
            backend:
              service:
                name: prometheus-server
                port:
                  number: 80