apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  ports:
    - name: node-svc
      port: 8888
      protocol: TCP
      targetPort: 8888
      nodePort: 32000
  selector:
    app: node-app
  type: NodePort
