agent:
  configMap:
    content: |
      faro.receiver "default" {
        server {
          cors_allowed_origins = ["*"]
        }
        output {
            logs   = [loki.write.default.receiver]
        }
      }

      loki.write "default" {
          endpoint {
              url = "http://loki-gateway/loki/api/v1/push"
          }
      }
  uiPathPrefix: "/agent-grafana"
serviceMonitor:
  enabled: true
