agent:
  configMap:
    content: |
      faro.receiver "default" {
        server {
          listen_address = "0.0.0.0"
          cors_allowed_origins = ["*"]
        }
        output {
            logs   = [loki.write.default.receiver]
        }
        extra_log_labels = {
          app = "frontend",
        }
      }

      loki.write "default" {
          endpoint {
              url = "http://loki-gateway/loki/api/v1/push"
          }
      }
  uiPathPrefix: "/agent-grafana"
  extraPorts:
    - name: "faro"
      port: 12347
      targetPort: 12347
      protocol: "TCP"
serviceMonitor:
  enabled: true
