agent:
  configMap:
    content: |
      faro.receiver "default" {
        server {
          listen_address = "0.0.0.0"
          cors_allowed_origins = ["*"]
          listen_port = 8111
        }
        output {
            logs   = [loki.write.default.receiver]
        }
      }

      loki.write "default" {
          endpoint {
              url = "http://loki-gateway/loki/api/v1/push"
          }
      }
  uiPathPrefix: "/agent-grafana"
  extraPorts:
    - name: "faro"
      port: 8111
      targetPort: 8111
      protocol: "TCP"
serviceMonitor:
  enabled: true
