loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
singleBinary:
  persistence:
    size: 3Gi
    storageClass: local-storage-class
  replicas: 1
tableManager:
  retention_deletes_enabled: true
  retention_period: 7d
