loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  ingester:
    wal:
      enabled: false
singleBinary:
  persistence:
    size: 3Gi
    storageClass: local-storage-class
  replicas: 1
