apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-healthvue
  namespace: healthvue

spec:
  entryPoints:
    - web

  routes:
    - match: PathPrefix(`/healthvue`)
      kind: Rule
      services:
        - name: healthvue
          port: 80
