apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-minio
  namespace: minio

spec:
  entryPoints:
    - web

  routes:
    - match: PathPrefix(`/minio`)
      kind: Rule
      services:
          port: 9001
      middlewares:
        - name: stripprefix-minio

